# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemodel',
            name='name',
            field=models.CharField(default='Price Model', max_length=50),
        ),
    ]
