# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
