# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_email'),
        ('payment', '0004_auto_20170129_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=50)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='paying_customer', to='customers.Customer')),
                ('customer_to_transfer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_to_transfer', to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
