# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('paytm', 'Paytm'), ('account', 'Account Transfer'), ('cash', 'Cash'), ('other', 'Others'), ('skiltil-transfer', 'Skiltil Internal Transfer')], default='paytm', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='mode',
            field=models.CharField(choices=[('paytm', 'Paytm'), ('account', 'Account Transfer'), ('cash', 'Cash'), ('other', 'Others'), ('skiltil-transfer', 'Skiltil Internal Transfer')], default='paytm', max_length=20),
        ),
    ]
