"""
Django settings for projectX project.
Generated by 'django-admin startproject' using Django 1.10.3.
For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import raven
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', "RAVEN SECRET KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', True)

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'proj.apps.ProjConfig',
    'customers.apps.CustomersConfig',
    'session.apps.SessionConfig',
    'payment.apps.PaymentConfig',
    'base.apps.BaseConfig',
    # 'material',
    # 'material.frontend',
    # 'material.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'raven.contrib.django.raven_compat',
    'analytical',
    'django.contrib.sitemaps',
    'tinymce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projectX.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'projectX.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASE_NAME = os.getenv('DATABASE_NAME', 'MY DB NAME')
DATABASE_USER = os.getenv('DATABASE_USER', 'MY DB USER')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD', 'MY DB PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST', 'MY HOST')
DATABASE_PORT = os.getenv('DATABASE_PORT', 'MY PORT')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_FILE_PATH = '~/Documents/app-messages'
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_SENDER', 'MY EMAIL SENDER')
EMAIL_HOST = os.getenv('EMAIL_PROVIDER', 'MY EMAIL PROVIDER')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'MY EMAIL HOST USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'MY EMAIL HOST PASSWORD')
# EMAIL_USE_TLS = False
EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
EMAIL_USE_TLS = True

# CLICKY_SITE_ID = '101008337'

# RAVEN_CONFIG = {
#	'dsn': 'https://41ec5e53e81f42a98a8c5f2de541fa94:c6e43498554a440f8cff16cc95a83417@sentry.io/119904',
#	# If you are using git, you can also automatically configure the
#	# release based on the git info.
#	'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),
# }

# logger = logging.getLogger("sentry.errors")
# handler = logging.StreamHandler()
# formatter = logging.Formatter("[%(levelname)s] %(name)s: %(message)s")
# handler.setFormatter(formatter)
# logger.addHandler(handler)