# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'OnGoing'), (1, 'Finished'), (2, 'Unfinished')])),
                ('follow_up', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('call_duration', models.DurationField(default=datetime.timedelta)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'OnGoing'), (1, 'Finished'), (2, 'Unfinished')])),
                ('follow_up', models.BooleanField()),
                ('total_calls', models.IntegerField(default=0)),
                ('total_duration', models.DurationField(default=datetime.timedelta)),
                ('minutes_duration', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 0, 521995, tzinfo=utc))),
                ('call_time_range', models.DurationField(default=datetime.timedelta)),
                ('time_refund', models.DurationField(default=datetime.timedelta)),
                ('money_refund', models.FloatField(default=0)),
                ('amount_to_teacher', models.FloatField(default=0)),
                ('amount_from_student', models.FloatField(default=0)),
                ('balance_amount', models.FloatField(default=0)),
                ('skill_match', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.SkillMatch')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='belong_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
    ]
