# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='date',
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, 0, 39876, tzinfo=utc)),
        ),
    ]
