# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0040_auto_20161222_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
    ]
