# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0041_session_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.IntegerField(choices=[(0, 'OnGoing'), (1, 'Finished'), (2, 'Unfinished')], default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(0, 'OnGoing'), (1, 'Finished'), (2, 'Unfinished')], default=1),
        ),
    ]
