# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0042_auto_20170108_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_mode',
            field=models.CharField(choices=[('skype', 'Skype'), ('gmail', 'Gmail'), ('appear', 'Appear.in'), ('imo', 'Imo'), ('zoom', 'Zoom'), ('phone', 'Phone'), ('chat', 'Chat'), ('sms', 'SMS'), ('others', 'Others')], default='skype', max_length=20),
        ),
    ]
