# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0043_call_call_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='monitored',
            field=models.CharField(choices=[('fully', 'Fully monitored'), ('partially', 'Partially Monitored'), ('notmonitor', 'Not Monitored'), ('couldnot', 'Could Not Monitor')], default='fully', max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='platform_tries',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='call',
            name='student_audible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='call',
            name='student_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='call',
            name='teacher_audible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='call',
            name='teacher_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='call',
            name='video_call_rating',
            field=models.IntegerField(choices=[(1, "Couldn't be copleted"), (2, 'Many breakages'), (3, 'No breakage but not a good call'), (4, 'Decent call without breakages'), (5, 'Excellent call')], default=4),
        ),
    ]
