# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0044_auto_20170129_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='student_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='student_rating',
            field=models.IntegerField(choices=[(-1, -1), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=-1),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher_rating',
            field=models.IntegerField(choices=[(-1, -1), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=-1),
        ),
    ]
