# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0045_auto_20170129_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='order_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
