# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-24 15:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0046_session_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='estimate_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='session',
            name='rescheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.IntegerField(choices=[(0, 'OnGoing'), (1, 'Finished'), (2, 'Unfinished'), (3, 'Scheduled')], default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(0, 'OnGoing'), (1, 'Finished'), (2, 'Unfinished'), (3, 'Scheduled')], default=3),
        ),
    ]
