# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20170302_0952'),
        ('session', '0047_auto_20170224_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='student_pricing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.PriceModel'),
        ),
    ]
