# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20170302_0952'),
        ('session', '0048_session_student_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='teacher_pricing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_pricing', to='pricing.PriceModel'),
        ),
        migrations.AlterField(
            model_name='session',
            name='student_pricing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_pricing', to='pricing.PriceModel'),
        ),
    ]
