# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0050_auto_20170302_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_mode',
            field=models.CharField(choices=[('skype', 'Skype'), ('gmail', 'Gmail Call'), ('appear', 'Appear.in'), ('imo', 'Imo'), ('whatsapp', 'Whatsapp Call'), ('facebook', 'Facebook Call'), ('zoom', 'Zoom'), ('phone', 'Phone'), ('chat', 'Chat'), ('sms', 'SMS'), ('others', 'Others')], default='skype', max_length=20),
        ),
    ]
