# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20161120_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltopic',
            name='topic_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
