# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_skilltopic_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
