# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_skill_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_src',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
