# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_skill_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
