# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0010_skill_no_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
