# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0011_auto_20161222_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.CharField(blank=True, max_length=50)),
                ('preferred_communication_time', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
