# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0012_customerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='skill',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
