# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0013_customerrequest_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='default_skill',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
