# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0014_customerrequest_default_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='details',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image_src',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
