# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0015_auto_20170126_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_code',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
