# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0016_skill_skill_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltopic',
            name='topic_code',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
