# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 13:07
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0017_skilltopic_topic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='details',
            field=tinymce.models.HTMLField(blank=True, default=b''),
        ),
    ]
