# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0018_auto_20170225_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='first_class_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='skill',
            name='subsequent_class_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='skill',
            name='total_classes',
            field=models.IntegerField(default=1),
        ),
    ]
