# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0019_auto_20170225_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='first_class_time',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='skill',
            name='subsequent_class_time',
            field=models.DurationField(blank=True, default=datetime.timedelta),
        ),
    ]
