# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 15:12
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0020_auto_20170225_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='pre_requisites',
            field=tinymce.models.HTMLField(blank=True, default=b''),
        ),
    ]
