# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20170302_0952'),
        ('proj', '0022_auto_20170301_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='student_pricing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_student_pricing', to='pricing.PriceModel'),
        ),
        migrations.AddField(
            model_name='skill',
            name='teacher_pricing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_teacher_pricing', to='pricing.PriceModel'),
        ),
    ]
