# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0023_auto_20170302_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='first_class_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0, 1800)),
        ),
    ]
