# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0025_skill_course_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltopic',
            name='topic_pic',
            field=models.ImageField(null=True, upload_to=b'images/'),
        ),
    ]
