# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0027_auto_20170325_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
