# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0030_auto_20170402_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=50)),
                ('event_code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='events',
            field=models.ManyToManyField(to='proj.Event'),
        ),
    ]
