# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0031_auto_20170404_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltopic',
            name='events',
        ),
        migrations.AddField(
            model_name='skill',
            name='events',
            field=models.ManyToManyField(to='proj.Event'),
        ),
    ]
