# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0032_auto_20170404_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='events',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
