# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import proj.models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0033_auto_20170409_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltopic',
            name='topic_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=proj.models.content_file_name),
        ),
    ]
