# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0034_auto_20170409_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltopic',
            name='parent_topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.SkillTopic'),
        ),
    ]
