# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0035_auto_20170409_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('skilltopic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proj.SkillTopic')),
            ],
            options={
                'abstract': False,
            },
            bases=('proj.skilltopic',),
        ),
        migrations.AddField(
            model_name='skilltopic',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skill_topic', to='proj.SkillTopic'),
        ),
        migrations.AddField(
            model_name='skill',
            name='events',
            field=models.ManyToManyField(related_name='events', to='proj.Event'),
        ),
    ]
