# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0036_auto_20170411_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltopic',
            name='is_event',
        ),
        migrations.AddField(
            model_name='event',
            name='is_event',
            field=models.BooleanField(default=True),
        ),
    ]
