# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0037_auto_20170411_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='proj.Event'),
        ),
    ]
