# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proj', '0008_skilltopic_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('skype_id', models.CharField(max_length=200)),
                ('gmail_id', models.CharField(max_length=200)),
                ('wallet_amount', models.IntegerField(default=0)),
                ('classes_taken', models.IntegerField(default=0)),
                ('classes_given', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('skill', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proj.Skill')),
            ],
        ),
    ]
