# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20161211_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmatch',
            name='classes_given',
            field=models.IntegerField(default=0),
        ),
    ]
