# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20161211_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmatch',
            name='details',
            field=models.TextField(default=b''),
        ),
    ]
