# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_skillmatch_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_subjects',
            field=models.IntegerField(default=0),
        ),
    ]
