# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_no_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmatch',
            name='details',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
