# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[(b'f', b'Female'), (b'm', b'Male'), (b'o', b'Other'), (b'd', b'Decline to State')], default=b'd', max_length=1),
        ),
    ]
