# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
