# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customer_customer_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_code',
            new_name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
