# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20170201_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user_name',
        ),
    ]
