# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_customer_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmatch',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
