# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_skillmatch_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmatch',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
