# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_auto_20170204_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default=b'', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
