# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0006_partial'),
        ('customers', '0018_auto_20170205_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='social',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
